// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3iCJe45bjEFHtLaXyrdMnXa6WCp8GdU4',
    appId: '1:1066215068381:web:2784f1041bbd9a4c9dc134',
    messagingSenderId: '1066215068381',
    projectId: 'andaluciapesca-cbda7',
    authDomain: 'andaluciapesca-cbda7.firebaseapp.com',
    storageBucket: 'andaluciapesca-cbda7.appspot.com',
    measurementId: 'G-K0BNVXR4XS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCiR5jPcICs7GcvQ184oLZEZS3pDbZWaGU',
    appId: '1:1066215068381:android:26b4dc48f380061d9dc134',
    messagingSenderId: '1066215068381',
    projectId: 'andaluciapesca-cbda7',
    storageBucket: 'andaluciapesca-cbda7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDh8UmjW70Mi7Ep7LcoH86YXYPjRNU80uM',
    appId: '1:1066215068381:ios:d7e04b045fda380f9dc134',
    messagingSenderId: '1066215068381',
    projectId: 'andaluciapesca-cbda7',
    storageBucket: 'andaluciapesca-cbda7.appspot.com',
    androidClientId: '1066215068381-3jhip653hrhevoilk4j311q32na22o9u.apps.googleusercontent.com',
    iosClientId: '1066215068381-aq9rj5lpph4lm3mugd9gotpjeofbcl3k.apps.googleusercontent.com',
    iosBundleId: 'com.example.andaluciapesca',
  );
}
